[tool.black]
line-length = 100
target-version = ['py39']
include = '\.py$'
exclude = '''
/(\.git|__pycache__|build|dist)/
'''

[tool.ruff]
line-length = 100
select = ["E", "F", "B", "I"]
exclude = ["tests", "venv"]
